---
- hosts: backup
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Create a temp directory to store files needed by the run
      tempfile:
        state: directory
        prefix: "ansible-deploy-"
      register: _run_temp_dir
      notify:
        - clear caches
    - name: Install necessary software.
      dnf:
        name: "{{ _packages | join(',') }}"
        state: present
        update_cache: yes
      notify:
        - clear dnf cache
      vars:
        _packages:
          - "mariadb"
          - "openssh-clients"
          - "python3-chardet"
          - "python3-jmespath"
          - "python3-PyMySQL"
          - "python3-urllib3"
    - name: Install the additional packages from pip
      pip:
        name:
          - "s3cmd"
          - "boto3"
          - "botocore"
        extra_args: "--no-cache-dir"
    - name: Deploy key scripts.
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "backup"
        group: "backup"
        mode: "u=rx,g=rx,o="
      loop:
        - src: "templates/mysql-backup.sh.j2"
          dest: "/usr/local/bin/mysql-backup"
    - name: Create the backup directory
      file:
        path: "/backups"
        state: directory
        owner: "backup"
        group: "backup"
        mode: "u=rwx,g=rwx,o="
    - name: Update permissions of key directories
      file:
         path: "{{ item }}"
         state: directory
         owner: "backup"
         group: "backup"
         mode: "u=rwx,g=rwx,o="
      loop:
        - "/ansible"
        - "/home/backup/.ssh"       
        
  handlers:
    - name: clear caches
      shell: >
        rm -rf {{ item }}
      loop:
        - "/tmp/*"
        - "/var/www/.composer/cache"
        - "/root/.ansible/tmp"
        - "/root/.cache"

